# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - oraclejdk11

# используем режим обычного пользователя для сборки проекта.
sudo: false

install: true

script: mvn clean package -DskipTests=true

#services:
#postgresql
## Изменяет текущую временную зону.
before_install:
  - export TZ=Europe/Moscow
  - date
#  # JDBC создание базы данных
#  - psql -c 'create database forum;' -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
#after_success:
#  - bash <(curl -s https://codecov.io/bash)
#env:
#  global:
#    - CODECOV_TOKEN="59d8cd47-2c12-47ea-abab-d75d71719563"

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -roman9628@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
deploy:
  provider: heroku
  api_key:
    secure:
      cD4uAjkZxtl464UOhfxJdpIN4iHWWV7/jJSwl/n0upFpSlatAIXq/8JWSFhRIfjhyn2TFCY0U8yqCe2tUyeze+5lgLiyWSjN27GDQFRfC15lMl45RR76uUqPvBiL3pGr601JO0olY2JM7llhVWlxMv42MswotTDW2WvRGWAWwObjEmbDlYicfZl1Dlm9iCjh1BUF8+U7OOgFhyFo20uSlRR96tZ+0vlN7bhRdatCJ0umZxxsp3NziNNzGldvMvNhtDSp1a7jT/mJ9Wl1E7BYWlxYIFG1b/fW0K0iKmW3GDquiJoMNPz+n/PlWe+wwgoXVuDMlBhck6djfrmUj7Y2rYY3UE5QDHaqmYh7J6yE1txrkHUj3SJKFcuYAEd7NDwVHCYlwaWs6x82fjvI0YEfzAm1Z0Klho9vx3X6zzV19IOd165/pGlazxfmHIww/LHs7fw2Fzq7Q28ydZkSn/V60DCy/LO/WPb/wZNjfGRIFI44aYl1Pbu+MJ3A+L4dMztVDOmbFL0dqCFZDGdjeTkZGwowq65LirkHTmw460si5Xcf+rc3nb5BQAlVIiesRK3zChkIQabSZxADleVE1HuZhSE8NNmTSCNLnSw2TkfoUxNVYIpDdW7iP/QmEAyEi9+EJn7aKRTREvByUrNK4zC1cToNaYoT30wrGeeJ3ak+s4Q=
  app: desolate-cove-18741

