# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - oraclejdk11

# используем режим обычного пользователя для сборки проекта.
sudo: false

#services:
postgresql
## Изменяет текущую временную зону.
before_install:
  - chmod +x mvnw
  - export TZ=Europe/Moscow
  - date
#  # JDBC создание базы данных
  - psql -c 'create database forum;' -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - CODECOV_TOKEN="004d72e2-32d5-4f60-bc22-ef83bb9bdeca"

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -roman9628@gmail.com
    on_success: never # default: change
    on_failure: always # default: always